"""PoC watermarking — HMAC-based provenance stamps on generated payloads.

Every payload generated by ARGUS is watermarked with an HMAC
derived from scan_id + tenant_id + timestamp. This proves the
payload originated from a specific ARGUS scan and enables
accountability/tracing without revealing secrets.

Ось E п.2 из Развитие2.md: PoC watermarking.
"""

from __future__ import annotations

import hashlib
import hmac
import logging
import time
from dataclasses import dataclass
from typing import Any

logger = logging.getLogger(__name__)

WATERMARK_PREFIX = "ARGUS-WM:"
WATERMARK_ALGORITHM = "sha256"


@dataclass(frozen=True)
class Watermark:
    """Provenance watermark for a generated payload."""

    scan_id: str
    tenant_id: str
    timestamp: float
    hmac_hex: str

    def to_string(self) -> str:
        return f"{WATERMARK_PREFIX}{self.hmac_hex[:16]}"

    def to_dict(self) -> dict[str, Any]:
        return {
            "scan_id": self.scan_id,
            "tenant_id": self.tenant_id,
            "timestamp": self.timestamp,
            "hmac_hex": self.hmac_hex,
        }


def generate_watermark(
    scan_id: str,
    tenant_id: str,
    secret_key: str,
    timestamp: float | None = None,
) -> Watermark:
    """Generate an HMAC watermark for a specific scan+tenant.

    The HMAC covers: scan_id + tenant_id + timestamp.
    The secret_key should be a per-deployment secret (from env/config).
    """
    ts = timestamp or time.time()
    message = f"{scan_id}:{tenant_id}:{ts:.6f}"
    mac = hmac.new(
        secret_key.encode("utf-8"),
        message.encode("utf-8"),
        WATERMARK_ALGORITHM,
    )
    return Watermark(
        scan_id=scan_id,
        tenant_id=tenant_id,
        timestamp=ts,
        hmac_hex=mac.hexdigest(),
    )


def verify_watermark(watermark: Watermark, secret_key: str) -> bool:
    """Verify a watermark against the deployment secret."""
    regenerated = generate_watermark(
        scan_id=watermark.scan_id,
        tenant_id=watermark.tenant_id,
        secret_key=secret_key,
        timestamp=watermark.timestamp,
    )
    return hmac.compare_digest(regenerated.hmac_hex, watermark.hmac_hex)


def stamp_payload(
    payload: str,
    scan_id: str,
    tenant_id: str,
    secret_key: str,
) -> str:
    """Add a watermark comment/stamp to a generated payload.

    Inserts a comment with the watermark into the payload.
    Format depends on payload type (shell, SQL, HTTP, etc.)
    """
    wm = generate_watermark(scan_id, tenant_id, secret_key)
    stamp = wm.to_string()

    stamp_suffix = f" # {stamp}"

    if payload.strip().endswith(";"):
        return payload + stamp_suffix
    if "\n" in payload:
        return payload + "\n" + stamp_suffix
    return payload + stamp_suffix


def extract_watermark_from_payload(payload: str) -> str | None:
    """Extract watermark string from a stamped payload."""
    if WATERMARK_PREFIX not in payload:
        return None
    idx = payload.find(WATERMARK_PREFIX)
    candidate = payload[idx:idx + len(WATERMARK_PREFIX) + 16]
    if len(candidate) >= len(WATERMARK_PREFIX) + 8:
        return candidate
    return None


__all__ = [
    "Watermark",
    "WATERMARK_PREFIX",
    "extract_watermark_from_payload",
    "generate_watermark",
    "stamp_payload",
    "verify_watermark",
]