"""Integrity verification for the runtime Jinja2 prompt templates.

The Ed25519-signed catalog under ``config/prompts/`` only covers the
``llm_orchestrator`` agent prompts (planner/critic/verifier/fixer/reporter).
The prompts that actually drive the live scan pipeline are the ``*.j2``
templates under ``src/orchestration/prompts/`` (see :mod:`prompt_loader`).
Those templates were previously loaded with **no** integrity guarantee
(F-M04), so a tampered template on a running container would render silently.

This module closes that gap with a SHA-256 manifest committed next to the
templates. Verification is **on by default** (``settings.prompt_integrity_enabled``,
default ``True``) and **fail-closed**: any drift between the on-disk templates
and the manifest raises :class:`PromptIntegrityError`, which aborts loader
initialisation and therefore the scan, rather than proceeding with unverified
prompts. Operators may opt out on a dev box via
``ARGUS_PROMPT_INTEGRITY_ENABLED=false``; the committed manifest is kept in sync
with the templates by a drift-guard test.

The manifest is a plain-text digest list (not an Ed25519 signature) because the
offline private signing key is intentionally not available in the repo. It is
therefore tamper-*evident* for the running container relative to the release
artifact, and a drift-guard test keeps it in sync with the templates in the
repository. Upgrading to a full Ed25519 signature is a follow-up that requires
the offline key (see ``BACKLOG.md``).
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Final

_MANIFEST_FILENAME: Final = "MANIFEST.sha256"
_TEMPLATE_GLOB: Final = "*.j2"
_CHUNK_SIZE: Final = 65536


class PromptIntegrityError(RuntimeError):
    """Raised when runtime prompt templates diverge from the signed manifest."""


def manifest_path(prompts_dir: Path) -> Path:
    """Return the canonical manifest location for *prompts_dir*."""
    return prompts_dir / _MANIFEST_FILENAME


def _digest_file(path: Path) -> str:
    """Return the hex SHA-256 of *path*, streamed to bound memory use."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(_CHUNK_SIZE), b""):
            digest.update(chunk)
    return digest.hexdigest()


def compute_manifest(prompts_dir: Path) -> dict[str, str]:
    """Compute ``{relative_posix_path: sha256_hex}`` for every ``.j2`` template."""
    result: dict[str, str] = {}
    for template in sorted(prompts_dir.rglob(_TEMPLATE_GLOB)):
        if not template.is_file():
            continue
        rel = template.relative_to(prompts_dir).as_posix()
        result[rel] = _digest_file(template)
    return result


def render_manifest(entries: dict[str, str]) -> str:
    """Serialise *entries* into the on-disk manifest text (deterministic)."""
    lines = [
        "# ARGUS runtime prompt template manifest",
        "# format: <sha256_hex>  <relative_path>",
        "# generated by: python backend/scripts/prompt_templates_manifest.py generate",
    ]
    lines.extend(f"{sha}  {rel}" for rel, sha in sorted(entries.items()))
    return "\n".join(lines) + "\n"


def parse_manifest(text: str) -> dict[str, str]:
    """Parse manifest *text* into ``{relative_path: sha256_hex}``.

    Comment (``#``) and blank lines are ignored. A malformed data line raises
    :class:`PromptIntegrityError` so a corrupt manifest fails closed.
    """
    entries: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(maxsplit=1)
        if len(parts) != 2:
            raise PromptIntegrityError("malformed manifest line")
        sha, rel = parts[0].strip(), parts[1].strip()
        if len(sha) != 64:
            raise PromptIntegrityError("malformed sha256 digest in manifest")
        entries[rel] = sha
    return entries


def load_manifest(prompts_dir: Path) -> dict[str, str]:
    """Load and parse the committed manifest for *prompts_dir* (fail-closed)."""
    path = manifest_path(prompts_dir)
    if not path.is_file():
        raise PromptIntegrityError("prompt template manifest is missing")
    return parse_manifest(path.read_text(encoding="utf-8"))


def diff_manifest(
    expected: dict[str, str], actual: dict[str, str]
) -> tuple[list[str], list[str], list[str]]:
    """Return ``(missing, extra, mismatched)`` relative paths comparing manifests.

    * ``missing`` — in *expected* manifest but absent on disk.
    * ``extra`` — on disk but absent from the manifest.
    * ``mismatched`` — present in both but with differing digests.
    """
    expected_paths = set(expected)
    actual_paths = set(actual)
    missing = sorted(expected_paths - actual_paths)
    extra = sorted(actual_paths - expected_paths)
    mismatched = sorted(
        rel for rel in expected_paths & actual_paths if expected[rel] != actual[rel]
    )
    return missing, extra, mismatched


def verify_templates(prompts_dir: Path) -> None:
    """Verify on-disk templates against the committed manifest (fail-closed).

    Raises :class:`PromptIntegrityError` on a missing manifest or any drift.
    """
    expected = load_manifest(prompts_dir)
    actual = compute_manifest(prompts_dir)
    missing, extra, mismatched = diff_manifest(expected, actual)
    if missing or extra or mismatched:
        raise PromptIntegrityError(
            "prompt template integrity check failed: "
            f"missing={missing} extra={extra} mismatched={mismatched}"
        )


def write_manifest(prompts_dir: Path) -> Path:
    """Recompute and atomically write the manifest for *prompts_dir*."""
    entries = compute_manifest(prompts_dir)
    path = manifest_path(prompts_dir)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(render_manifest(entries), encoding="utf-8")
    tmp.replace(path)
    return path


__all__ = [
    "PromptIntegrityError",
    "compute_manifest",
    "diff_manifest",
    "load_manifest",
    "manifest_path",
    "parse_manifest",
    "render_manifest",
    "verify_templates",
    "write_manifest",
]
