"""Quick execution mode — resolver, budget, planner, workflow, and domain types.

``execution_mode=quick`` is a third immutable profile alongside production
and lab_unrestricted. Policy is production-like; it never inherits LAB
allow-all.

Wall-clock leases in :class:`QuickBudgetManager` are independent of USD
``CostTracker``; the wall-clock deadline wins when they conflict.
"""

from __future__ import annotations

from src.quick.applicability import is_applicable
from src.quick.budget import (
    BudgetExhaustedError,
    BudgetLease,
    ConcurrencyLimitError,
    DiscoveryReserveProtectedError,
    LeaseExpiredError,
    LeaseStatus,
    QuickBudgetError,
    QuickBudgetManager,
    QuickBudgetSnapshot,
    assert_reserve_invariant,
    compute_deadline_at,
    reserve_seconds,
    stage_budget_sum,
)
from src.quick.cancellation import (
    CancellationResult,
    ScanCancelledError,
    is_scan_cancelled,
    mark_scan_cancelled,
    propagate_scan_cancellation,
    register_celery_task_id,
    revoke_scan_workers,
    scan_row_is_cancelled,
)
from src.quick.circuit_breaker import (
    CIRCUIT_OPEN_REASON,
    QuickCircuitBreaker,
    default_circuit_breaker,
)
from src.quick.clock import Clock, FrozenClock, SystemClock, as_utc
from src.quick.correlation import (
    CorrelatedFinding,
    LateOastResult,
    append_late_oast,
    correlate_results,
    mark_duplicate_occurrences,
    needs_selective_verification,
    overlay_ai_triage,
    scan_must_not_reopen,
    select_verification_candidates,
    to_lifecycle_occurrences,
    to_logical_finding,
)
from src.quick.coverage import (
    REASON_BUDGET_PARTIAL,
    REASON_DEADLINE_REACHED,
    REASON_EXECUTED,
    REASON_FINGERPRINT_MISMATCH,
    REASON_TOOL_ERROR,
    coverage_accounting_rate,
    ensure_planned_coverage,
    map_quick_state_to_status,
    signal_from_quick_record,
    write_quick_coverage,
)
from src.quick.disallowed import (
    DISALLOWED_TOOL_IDS,
    NOT_SCHEDULED_BY_QUICK_PROFILE,
    QuickDisallowedReason,
)
from src.quick.idempotency import (
    IdempotencyClaim,
    QuickIdempotencyStore,
    build_idempotency_key,
    default_idempotency_store,
)
from src.quick.llm_routes import (
    QuickLlmResult,
    catalog_tool_ids,
    classify_fingerprint,
    classify_fingerprints_batch,
    critique_finding,
    generate_report,
    plan_with_ai,
    render_quick_prompt,
    triage_finding,
)
from src.quick.llm_schemas import (
    LlmSchemaError,
    contains_shell_command,
    parse_llm_critique,
    parse_llm_fingerprint,
    parse_llm_plan,
    parse_llm_report,
    parse_llm_triage,
    tool_id_is_catalog_safe,
)
from src.quick.metrics import (
    admit_tracked_tool,
    record_assets_discovered,
    record_coverage_ratio,
    record_deadline_overrun,
    record_llm_call,
    record_plan_revision,
    record_task,
    record_templates_selected,
    record_tool_failure,
)
from src.quick.normalize import (
    QuickEvidenceDTO,
    QuickFindingDTO,
    QuickNormalizationResult,
    QuickNormalizeContext,
    QuickOccurrenceDTO,
    normalize_match,
    normalize_tool_output,
)
from src.quick.planner import (
    QuickPlanCandidate,
    QuickPlanner,
    QuickPlannerRequest,
    QuickPlannerTarget,
    plan_for_va_target,
)
from src.quick.profiles import (
    DeploymentQuickClamps,
    QuickProfileCatalog,
    QuickProfileCatalogError,
    QuickProfileDefaults,
    TenantQuickLimits,
    load_quick_profiles,
)
from src.quick.provenance import (
    FINGERPRINT_VERSION,
    QuickProvenance,
    build_provenance,
    compute_evidence_hash,
    digest_template_ids,
    evidence_json_for_llm,
    mint_evidence_id,
    public_fingerprint,
    redact_mapping_for_llm,
)
from src.quick.rag_profile import (
    QUICK_RAG_PROFILE_ID,
    QuickRagProfile,
    deny_lab_research,
    format_quick_rag_for_prompt,
)
from src.quick.resolver import (
    QuickProfileRequest,
    QuickProfileResolver,
    UnknownQuickProfileError,
    parse_quick_profile_name,
)
from src.quick.scheduler import (
    QuickScheduler,
    SchedulePick,
    ScheduleSkipReason,
    deadline_from_options,
    get_quick_budget_manager,
    seconds_until_deadline,
)
from src.quick.schemas import (
    AssetFingerprint,
    FindingTriage,
    FingerprintFact,
    QuickBudget,
    QuickCoverageRecord,
    QuickPlanRevision,
    QuickProfileName,
    QuickReport,
    QuickScanConfig,
    QuickScanPlan,
    QuickTask,
    SecurityCritique,
)
from src.quick.scoring import (
    ScoringComponents,
    ScoringWeights,
    compute_priority,
    tie_break_key,
)
from src.quick.template_selector import QuickTemplateSelector
from src.quick.workflow import (
    QUICK_PHASE_ALLOWLIST,
    SKIPPED_BY_QUICK_PROFILE,
    STAGE_ORDER,
    QuickWorkflow,
    is_quick_execution,
    phase_allowed,
    resolve_quick_plan,
    skip_reason_for_phase,
    skipped_phase_payload,
    skipped_phases_for_options,
)

__all__ = [
    "CIRCUIT_OPEN_REASON",
    "DISALLOWED_TOOL_IDS",
    "FINGERPRINT_VERSION",
    "NOT_SCHEDULED_BY_QUICK_PROFILE",
    "QUICK_PHASE_ALLOWLIST",
    "QUICK_RAG_PROFILE_ID",
    "REASON_BUDGET_PARTIAL",
    "REASON_DEADLINE_REACHED",
    "REASON_EXECUTED",
    "REASON_FINGERPRINT_MISMATCH",
    "REASON_TOOL_ERROR",
    "SKIPPED_BY_QUICK_PROFILE",
    "STAGE_ORDER",
    "AssetFingerprint",
    "BudgetExhaustedError",
    "BudgetLease",
    "CancellationResult",
    "Clock",
    "ConcurrencyLimitError",
    "CorrelatedFinding",
    "DeploymentQuickClamps",
    "DiscoveryReserveProtectedError",
    "FindingTriage",
    "FingerprintFact",
    "FrozenClock",
    "IdempotencyClaim",
    "LeaseExpiredError",
    "LeaseStatus",
    "LateOastResult",
    "LlmSchemaError",
    "QuickBudget",
    "QuickBudgetError",
    "QuickBudgetManager",
    "QuickBudgetSnapshot",
    "QuickCircuitBreaker",
    "QuickCoverageRecord",
    "QuickDisallowedReason",
    "QuickEvidenceDTO",
    "QuickFindingDTO",
    "QuickIdempotencyStore",
    "QuickLlmResult",
    "QuickNormalizationResult",
    "QuickNormalizeContext",
    "QuickOccurrenceDTO",
    "QuickPlanCandidate",
    "QuickPlanRevision",
    "QuickPlanner",
    "QuickPlannerRequest",
    "QuickPlannerTarget",
    "QuickProfileCatalog",
    "QuickProfileCatalogError",
    "QuickProfileDefaults",
    "QuickProfileName",
    "QuickProfileRequest",
    "QuickProfileResolver",
    "QuickProvenance",
    "QuickRagProfile",
    "QuickReport",
    "QuickScanConfig",
    "QuickScanPlan",
    "QuickScheduler",
    "QuickTask",
    "QuickTemplateSelector",
    "QuickWorkflow",
    "ScanCancelledError",
    "SchedulePick",
    "ScheduleSkipReason",
    "ScoringComponents",
    "ScoringWeights",
    "SecurityCritique",
    "SystemClock",
    "TenantQuickLimits",
    "UnknownQuickProfileError",
    "admit_tracked_tool",
    "as_utc",
    "assert_reserve_invariant",
    "append_late_oast",
    "build_idempotency_key",
    "build_provenance",
    "catalog_tool_ids",
    "classify_fingerprint",
    "classify_fingerprints_batch",
    "compute_deadline_at",
    "compute_evidence_hash",
    "compute_priority",
    "contains_shell_command",
    "correlate_results",
    "coverage_accounting_rate",
    "critique_finding",
    "deadline_from_options",
    "default_circuit_breaker",
    "default_idempotency_store",
    "deny_lab_research",
    "digest_template_ids",
    "ensure_planned_coverage",
    "evidence_json_for_llm",
    "format_quick_rag_for_prompt",
    "generate_report",
    "get_quick_budget_manager",
    "is_applicable",
    "is_quick_execution",
    "is_scan_cancelled",
    "load_quick_profiles",
    "map_quick_state_to_status",
    "mark_duplicate_occurrences",
    "mark_scan_cancelled",
    "mint_evidence_id",
    "needs_selective_verification",
    "normalize_match",
    "normalize_tool_output",
    "overlay_ai_triage",
    "parse_llm_critique",
    "parse_llm_fingerprint",
    "parse_llm_plan",
    "parse_llm_report",
    "parse_llm_triage",
    "parse_quick_profile_name",
    "phase_allowed",
    "plan_for_va_target",
    "plan_with_ai",
    "propagate_scan_cancellation",
    "record_assets_discovered",
    "record_coverage_ratio",
    "record_deadline_overrun",
    "record_llm_call",
    "record_plan_revision",
    "record_task",
    "record_templates_selected",
    "record_tool_failure",
    "register_celery_task_id",
    "render_quick_prompt",
    "reserve_seconds",
    "resolve_quick_plan",
    "revoke_scan_workers",
    "scan_row_is_cancelled",
    "seconds_until_deadline",
    "skip_reason_for_phase",
    "skipped_phase_payload",
    "skipped_phases_for_options",
    "stage_budget_sum",
    "tie_break_key",
    "tool_id_is_catalog_safe",
    "triage_finding",
]
