"""Kali pentest tool registry — 150+ tool definitions for MCP.

Each tool maps to backend API: POST /api/v1/tools/{name} or /execute.
Excludes exploit/brute-only tools per MCP-002.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class ArgSchema:
    """Argument schema for a tool."""

    name: str
    description: str
    required: bool = True
    default: Any = None
    type: str = "string"


@dataclass
class ToolDefinition:
    """Definition of a Kali pentest tool for MCP registration."""

    name: str
    description: str
    category: str
    backend_endpoint: str  # "nmap" | "execute" | tool-specific
    args_schema: list[ArgSchema] = field(default_factory=list)


def _arg(name: str, desc: str, required: bool = True, default: Any = None, type: str = "string") -> ArgSchema:
    return ArgSchema(name=name, description=desc, required=required, default=default, type=type)


# ---------------------------------------------------------------------------
# 150+ Kali tool definitions
# ---------------------------------------------------------------------------

KALI_TOOL_REGISTRY: list[ToolDefinition] = [
    # --- Recon: Subdomain/DNS (25) ---
    ToolDefinition(
        name="subfinder",
        description="Passive subdomain enumeration using public sources",
        category="recon",
        backend_endpoint="subfinder",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="amass",
        description="In-depth subdomain enumeration and asset discovery",
        category="recon",
        backend_endpoint="amass",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="httpx",
        description="Fast HTTP probing and title/tech detection",
        category="recon",
        backend_endpoint="httpx",
        args_schema=[_arg("targets", "URLs or domains (comma-separated)"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="whatweb",
        description="Web technology fingerprinting",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("target", "URL to fingerprint"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="dnsx",
        description="DNS toolkit: A/AAAA/CNAME/MX/TXT lookup",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Domain to query"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="naabu",
        description="Fast port scanner with SYN scan",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Host or IP"), _arg("ports", "Port list", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="theharvester",
        description="Gather emails, subdomains, hosts from public sources",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("source", "Data source (e.g. bing, google)", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="dnsrecon",
        description="DNS enumeration and reconnaissance",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="fierce",
        description="DNS reconnaissance for non-contiguous IP spaces",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="assetfinder",
        description="Find domains and subdomains related to a given domain",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="findomain",
        description="Cross-platform subdomain enumerator",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="gau",
        description="Get All URLs from AlienVault, Wayback Machine, etc.",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="waybackurls",
        description="Fetch all URLs from Wayback Machine for a domain",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="sublist3r",
        description="Subdomain enumeration using search engines",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="dig",
        description="DNS lookup utility",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Domain to query"), _arg("record_type", "Record type (A, AAAA, MX, etc.)", required=False, default="A"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="whois",
        description="WHOIS domain registration lookup",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Domain to query"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="host",
        description="DNS lookup utility",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Domain to query"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="nslookup",
        description="Query Internet name servers",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Domain to query"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="dnsenum",
        description="DNS enumeration: subdomains, reverse lookup, zone transfer",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="altdns",
        description="Generate permutations for subdomain discovery",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("wordlist", "Wordlist path", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="shuffledns",
        description="Mass DNS resolver with wildcard detection",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("wordlist", "Wordlist path", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="massdns",
        description="High-performance DNS stub resolver",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("resolvers", "Resolvers file", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="knockpy",
        description="Subdomain enumeration via wordlist",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="crt",
        description="Certificate Transparency log search (crt.sh)",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="curl",
        description="HTTP client for probing endpoints",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("url", "URL to fetch"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    # --- Vuln Scan (20) ---
    ToolDefinition(
        name="nuclei",
        description="Fast vulnerability scanner using YAML templates",
        category="vuln_scan",
        backend_endpoint="nuclei",
        args_schema=[
            _arg("target", "URL or domain to scan"),
            _arg("severity", "Filter by severity (critical, high, medium, low)", required=False, default=""),
            _arg("tags", "Template tags", required=False, default=""),
            _arg("template", "Specific template path", required=False, default=""),
            _arg("additional_args", "Extra CLI args", required=False, default=""),
        ],
    ),
    ToolDefinition(
        name="nikto",
        description="Web server vulnerability scanner",
        category="vuln_scan",
        backend_endpoint="nikto",
        args_schema=[_arg("target", "Target URL or host"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="nmap",
        description="Network mapper — port scan, service detection, OS fingerprinting",
        category="vuln_scan",
        backend_endpoint="nmap",
        args_schema=[
            _arg("target", "Target host or IP"),
            _arg("scan_type", "Scan type (-sV, -sS, -sC, etc.)", required=False, default="-sV"),
            _arg("ports", "Port specification", required=False, default=""),
            _arg("additional_args", "Extra CLI args", required=False, default="-T4 -Pn"),
        ],
    ),
    ToolDefinition(
        name="openvas",
        description="Open Vulnerability Assessment System",
        category="vuln_scan",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target IP or host"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="lynis",
        description="Security auditing for Unix/Linux",
        category="vuln_scan",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target path or system"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="sslyze",
        description="TLS/SSL configuration analyzer",
        category="vuln_scan",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Host:port to analyze"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="testssl",
        description="TLS/SSL testing for services",
        category="vuln_scan",
        backend_endpoint="execute",
        args_schema=[_arg("target", "URL or host:port"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="wapiti",
        description="Web application vulnerability scanner",
        category="vuln_scan",
        backend_endpoint="execute",
        args_schema=[_arg("url", "Target URL"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="zap",
        description="OWASP ZAP web app security scanner",
        category="vuln_scan",
        backend_endpoint="execute",
        args_schema=[_arg("url", "Target URL"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="retire",
        description="JavaScript library vulnerability scanner",
        category="vuln_scan",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to scan"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="safety",
        description="Check Python dependencies for known vulnerabilities",
        category="vuln_scan",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to requirements or project", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="npm_audit",
        description="Audit npm packages for vulnerabilities",
        category="vuln_scan",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to package.json", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="pip_audit",
        description="Audit Python packages for known vulnerabilities",
        category="vuln_scan",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to requirements", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="grype",
        description="Vulnerability scanner for containers and filesystems",
        category="vuln_scan",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Image or path to scan"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="trivy",
        description="Vulnerability scanner for containers, IaC, and more",
        category="vuln_scan",
        backend_endpoint="trivy",
        args_schema=[
            _arg("scan_type", "image, fs, repo, or config", required=False, default="image"),
            _arg("target", "Target to scan", required=False, default=""),
            _arg("additional_args", "Extra CLI args", required=False, default=""),
        ],
    ),
    ToolDefinition(
        name="clair",
        description="Container vulnerability scanner",
        category="vuln_scan",
        backend_endpoint="execute",
        args_schema=[_arg("image", "Container image to scan"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="cvedb",
        description="CVE database search and lookup",
        category="vuln_scan",
        backend_endpoint="execute",
        args_schema=[_arg("cve_id", "CVE identifier"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="searchsploit",
        description="Search Exploit-DB for exploits",
        category="vuln_scan",
        backend_endpoint="execute",
        args_schema=[_arg("query", "Search term"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="vulners",
        description="Vulnerability database search",
        category="vuln_scan",
        backend_endpoint="execute",
        args_schema=[_arg("query", "Search term"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    # --- Web (25) ---
    ToolDefinition(
        name="gobuster",
        description="Directory/DNS/vhost brute-forcing",
        category="web",
        backend_endpoint="gobuster",
        args_schema=[
            _arg("url", "Base URL"),
            _arg("mode", "dir, dns, fuzz, or vhost", required=False, default="dir"),
            _arg("wordlist", "Wordlist path", required=False, default="/usr/share/wordlists/dirb/common.txt"),
            _arg("additional_args", "Extra CLI args", required=False, default=""),
        ],
    ),
    ToolDefinition(
        name="ffuf",
        description="Fast web fuzzer",
        category="web",
        backend_endpoint="ffuf",
        args_schema=[
            _arg("url", "URL with FUZZ placeholder"),
            _arg("wordlist", "Wordlist path", required=False, default="/usr/share/wordlists/dirb/common.txt"),
            _arg("additional_args", "Extra CLI args", required=False, default=""),
        ],
    ),
    ToolDefinition(
        name="dirsearch",
        description="Web path scanner",
        category="web",
        backend_endpoint="dirsearch",
        args_schema=[
            _arg("url", "Target URL"),
            _arg("wordlist", "Wordlist path", required=False, default="/usr/share/wordlists/dirb/common.txt"),
            _arg("additional_args", "Extra CLI args", required=False, default=""),
        ],
    ),
    ToolDefinition(
        name="wfuzz",
        description="Web application fuzzer",
        category="web",
        backend_endpoint="wfuzz",
        args_schema=[
            _arg("url", "URL with FUZZ placeholder"),
            _arg("wordlist", "Wordlist path", required=False, default="/usr/share/wordlists/dirb/common.txt"),
            _arg("additional_args", "Extra CLI args", required=False, default=""),
        ],
    ),
    ToolDefinition(
        name="sqlmap",
        description="SQL injection detection and exploitation",
        category="web",
        backend_endpoint="sqlmap",
        args_schema=[_arg("url", "Target URL with injection point"), _arg("data", "POST data", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="dirb",
        description="Web content scanner",
        category="web",
        backend_endpoint="dirb",
        args_schema=[
            _arg("url", "Target URL"),
            _arg("wordlist", "Wordlist path", required=False, default="/usr/share/wordlists/dirb/common.txt"),
            _arg("additional_args", "Extra CLI args", required=False, default=""),
        ],
    ),
    ToolDefinition(
        name="feroxbuster",
        description="Fast, recursive content discovery",
        category="web",
        backend_endpoint="feroxbuster",
        args_schema=[
            _arg("url", "Target URL"),
            _arg("wordlist", "Wordlist path", required=False, default="/usr/share/wordlists/dirb/common.txt"),
            _arg("additional_args", "Extra CLI args", required=False, default=""),
        ],
    ),
    ToolDefinition(
        name="wpscan",
        description="WordPress vulnerability scanner",
        category="web",
        backend_endpoint="wpscan",
        args_schema=[_arg("url", "WordPress site URL"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="joomscan",
        description="Joomla vulnerability scanner",
        category="web",
        backend_endpoint="execute",
        args_schema=[_arg("url", "Joomla site URL"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="droopescan",
        description="Drupal, Silverstripe, WordPress scanner",
        category="web",
        backend_endpoint="execute",
        args_schema=[_arg("url", "Target URL"), _arg("cms", "CMS type", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="arjun",
        description="HTTP parameter discovery",
        category="web",
        backend_endpoint="execute",
        args_schema=[_arg("url", "Target URL"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="paramspider",
        description="Mine parameters from web archives",
        category="web",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="commix",
        description="Command injection exploiter",
        category="web",
        backend_endpoint="execute",
        args_schema=[_arg("url", "Target URL with injection point"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="xsstrike",
        description="XSS vulnerability scanner",
        category="web",
        backend_endpoint="execute",
        args_schema=[_arg("url", "Target URL"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="dalfox",
        description="Parameter analysis and XSS scanning",
        category="web",
        backend_endpoint="execute",
        args_schema=[_arg("url", "Target URL"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="nuclei_web",
        description="Nuclei with web-specific templates",
        category="web",
        backend_endpoint="nuclei",
        args_schema=[_arg("target", "Target URL"), _arg("tags", "Template tags (e.g. xss, sqli)", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="httpx_tech",
        description="httpx with technology detection",
        category="web",
        backend_endpoint="httpx",
        args_schema=[_arg("targets", "URLs to probe"), _arg("additional_args", "Extra CLI args", required=False, default="-tech-detect")],
    ),
    ToolDefinition(
        name="katana",
        description="Crawler for web discovery",
        category="web",
        backend_endpoint="execute",
        args_schema=[_arg("url", "Starting URL"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="gau_web",
        description="Get All URLs for web recon",
        category="web",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="hakrawler",
        description="Fast web crawler for link extraction",
        category="web",
        backend_endpoint="execute",
        args_schema=[_arg("url", "Target URL"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="gospider",
        description="Web spider written in Go",
        category="web",
        backend_endpoint="execute",
        args_schema=[_arg("url", "Target URL"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="burpsuite",
        description="Web security testing platform (CLI mode)",
        category="web",
        backend_endpoint="execute",
        args_schema=[_arg("url", "Target URL"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="cewl",
        description="Custom wordlist generator from target site",
        category="web",
        backend_endpoint="execute",
        args_schema=[_arg("url", "Target URL"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="crunch",
        description="Wordlist generator",
        category="web",
        backend_endpoint="execute",
        args_schema=[_arg("min_len", "Minimum length"), _arg("max_len", "Maximum length"), _arg("charset", "Character set", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    # --- Network (20) ---
    ToolDefinition(
        name="masscan",
        description="Mass IP port scanner",
        category="network",
        backend_endpoint="masscan",
        args_schema=[
            _arg("target", "Target IP or range"),
            _arg("ports", "Port specification", required=False, default="1-65535"),
            _arg("rate", "Packets per second", required=False, default="1000"),
            _arg("additional_args", "Extra CLI args", required=False, default=""),
        ],
    ),
    ToolDefinition(
        name="rustscan",
        description="Fast port scanner",
        category="network",
        backend_endpoint="rustscan",
        args_schema=[_arg("target", "Target host"), _arg("ports", "Port list", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="zmap",
        description="Internet-wide scanner",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target or port"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="unicornscan",
        description="Asynchronous network scanner",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target host"), _arg("ports", "Port specification", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="hping3",
        description="Network packet crafting and analysis",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target host"), _arg("mode", "Mode (e.g. -S for SYN)", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="netcat",
        description="Network utility for reading/writing connections",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target host"), _arg("port", "Port", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="ncat",
        description="Modern netcat from Nmap project",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target host"), _arg("port", "Port", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="snmpwalk",
        description="SNMP enumeration",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target host"), _arg("community", "SNMP community", required=False, default="public"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="onesixtyone",
        description="SNMP community string scanner",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target IP or file"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="enum4linux",
        description="SMB/LDAP enumeration for Windows",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target host"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="smbclient",
        description="SMB/CIFS client",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target share"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="nbtscan",
        description="NetBIOS name scanner",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target IP or range"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="rpcclient",
        description="RPC client for Windows enumeration",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target host"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="ldapsearch",
        description="LDAP query tool",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "LDAP server"), _arg("base_dn", "Base DN", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="traceroute",
        description="Trace route to host",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target host"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="ping",
        description="ICMP echo request",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target host"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="arp-scan",
        description="ARP scanner for local network",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target or interface"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="ike-scan",
        description="IPSec VPN scanner",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target VPN gateway"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="responder",
        description="LLMNR/NBT-NS poisoner (analysis mode)",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("interface", "Network interface", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="crackmapexec",
        description="Network penetration testing Swiss Army knife",
        category="network",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Target"), _arg("module", "Module to run", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    # --- Cloud (15) ---
    ToolDefinition(
        name="prowler",
        description="AWS security assessment",
        category="cloud",
        backend_endpoint="execute",
        args_schema=[_arg("profile", "AWS profile", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="scoutsuite",
        description="Multi-cloud security auditing",
        category="cloud",
        backend_endpoint="execute",
        args_schema=[_arg("provider", "aws, azure, gcp", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="cloudsplaining",
        description="AWS IAM policy analysis",
        category="cloud",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to IAM policy", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="steampipe",
        description="SQL-based cloud asset query",
        category="cloud",
        backend_endpoint="execute",
        args_schema=[_arg("query", "Steampipe query", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="tfsec",
        description="Terraform security scanner",
        category="cloud",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to Terraform", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="cfn_nag",
        description="CloudFormation security linter",
        category="cloud",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to template", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="kics",
        description="Infrastructure as Code scanner",
        category="cloud",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to scan", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="cloudsploit",
        description="Cloud security posture management",
        category="cloud",
        backend_endpoint="execute",
        args_schema=[_arg("provider", "Cloud provider", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="azucar",
        description="Azure security audit",
        category="cloud",
        backend_endpoint="execute",
        args_schema=[_arg("subscription", "Subscription ID", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="gcp_scanner",
        description="GCP security scanner",
        category="cloud",
        backend_endpoint="execute",
        args_schema=[_arg("project", "GCP project", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="kubeaudit",
        description="Kubernetes security auditor",
        category="cloud",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to manifests", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="kubescape",
        description="Kubernetes security platform",
        category="cloud",
        backend_endpoint="execute",
        args_schema=[_arg("target", "Cluster or manifest", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="polaris",
        description="Kubernetes configuration validation",
        category="cloud",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to manifests", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="kube_score",
        description="Kubernetes object security scoring",
        category="cloud",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to manifests", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    # --- Code / SAST (20) ---
    ToolDefinition(
        name="semgrep",
        description="Static analysis for security and correctness",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to scan"), _arg("config", "Rule config", required=False, default="auto"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="gitleaks",
        description="Secret detection in git repos",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to repo", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="trufflehog",
        description="Find credentials in git and other sources",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to scan", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="bandit",
        description="Python security linter",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to Python code"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="brakeman",
        description="Ruby on Rails security scanner",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to Rails app"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="spotbugs",
        description="Java bug detector",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to Java project"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="gosec",
        description="Go security checker",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to Go code"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="flawfinder",
        description="C/C++ vulnerability scanner",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to C/C++ code"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="cppcheck",
        description="C/C++ static analyzer",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to C/C++ code"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="eslint",
        description="JavaScript/TypeScript linter with security rules",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to JS/TS project"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="npm_audit_code",
        description="npm audit for dependency vulnerabilities",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to package.json", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="yarn_audit",
        description="Yarn audit for vulnerabilities",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to project", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="detect_secrets",
        description="Prevent committing secrets",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to scan", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="git_secrets",
        description="Prevent committing secrets to git",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to repo", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="repo_supervisor",
        description="Secret scanning for repos",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to repo", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="codeql",
        description="Semantic code analysis",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to codebase"), _arg("language", "Language", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="sonarscanner",
        description="SonarQube code quality and security",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to project"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="insidersec",
        description="SAST for multiple languages",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to scan"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="bearer",
        description="Code security scanning",
        category="code",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to scan"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    # --- IaC (15) ---
    ToolDefinition(
        name="checkov",
        description="Infrastructure as Code security scanner",
        category="iac",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to IaC files"), _arg("framework", "Framework (terraform, cloudformation, etc.)", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="terrascan",
        description="Terraform security scanner",
        category="iac",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to Terraform"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="tfsec_terraform",
        description="Terraform security scanner via tfsec",
        category="iac",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to Terraform"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="infracost",
        description="Cloud cost estimation for IaC",
        category="iac",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to Terraform"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="conftest",
        description="Test structured configuration files",
        category="iac",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to config"), _arg("policy", "Policy path", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="opa",
        description="Open Policy Agent for policy evaluation",
        category="iac",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to evaluate"), _arg("policy", "Policy file", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="regula",
        description="Rego-based IaC security",
        category="iac",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to IaC"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="policies",
        description="Policy as code validation",
        category="iac",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to config"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="docker_bench",
        description="Docker security benchmark",
        category="iac",
        backend_endpoint="execute",
        args_schema=[_arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="cis_docker",
        description="CIS Docker benchmark",
        category="iac",
        backend_endpoint="execute",
        args_schema=[_arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="ansible_lint",
        description="Ansible playbook linter",
        category="iac",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to playbooks"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="puppet_parser",
        description="Puppet manifest validation",
        category="iac",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to manifests"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="helm_lint",
        description="Helm chart linter",
        category="iac",
        backend_endpoint="execute",
        args_schema=[_arg("path", "Path to chart"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    # --- Misc / Forensics (10) ---
    ToolDefinition(
        name="binwalk",
        description="Firmware analysis and extraction",
        category="misc",
        backend_endpoint="execute",
        args_schema=[_arg("file", "Firmware or binary file"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="strings",
        description="Extract printable strings from binary",
        category="misc",
        backend_endpoint="execute",
        args_schema=[_arg("file", "Binary file"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="exiftool",
        description="Read/write metadata in files",
        category="misc",
        backend_endpoint="execute",
        args_schema=[_arg("file", "File to analyze"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="foremost",
        description="File carving and recovery",
        category="misc",
        backend_endpoint="execute",
        args_schema=[_arg("file", "Image or file"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="volatility",
        description="Memory forensics framework",
        category="misc",
        backend_endpoint="execute",
        args_schema=[_arg("image", "Memory dump"), _arg("plugin", "Volatility plugin", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="bulk_extractor",
        description="Extract features from disk images",
        category="misc",
        backend_endpoint="execute",
        args_schema=[_arg("image", "Disk image"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="hashcat",
        description="Password hash cracking (analysis mode)",
        category="misc",
        backend_endpoint="execute",
        args_schema=[_arg("hash", "Hash to crack", required=False, default=""), _arg("wordlist", "Wordlist", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="john",
        description="Password hash cracking",
        category="misc",
        backend_endpoint="execute",
        args_schema=[_arg("file", "Password file", required=False, default=""), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="pdfid",
        description="PDF structure analysis",
        category="misc",
        backend_endpoint="execute",
        args_schema=[_arg("file", "PDF file"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="pev",
        description="PE file analysis",
        category="misc",
        backend_endpoint="execute",
        args_schema=[_arg("file", "PE file"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="wpscan_cli",
        description="WordPress scanner (CLI mode)",
        category="web",
        backend_endpoint="wpscan",
        args_schema=[_arg("url", "WordPress URL"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="nmap_os",
        description="Nmap OS detection scan",
        category="vuln_scan",
        backend_endpoint="nmap",
        args_schema=[_arg("target", "Target host"), _arg("additional_args", "Extra CLI args", required=False, default="-O")],
    ),
    ToolDefinition(
        name="nikto_ssl",
        description="Nikto with SSL/TLS checks",
        category="vuln_scan",
        backend_endpoint="nikto",
        args_schema=[_arg("target", "Target URL"), _arg("additional_args", "Extra CLI args", required=False, default="-ssl")],
    ),
    ToolDefinition(
        name="dnsdumpster",
        description="DNS recon via DNSDumpster",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="builtwith",
        description="Technology lookup",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("domain", "Target domain"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
    ToolDefinition(
        name="shodan",
        description="Shodan search (CLI)",
        category="recon",
        backend_endpoint="execute",
        args_schema=[_arg("query", "Shodan search query"), _arg("additional_args", "Extra CLI args", required=False, default="")],
    ),
]


def get_tools_by_category() -> dict[str, list[ToolDefinition]]:
    """Group tools by category."""
    by_cat: dict[str, list[ToolDefinition]] = {}
    for t in KALI_TOOL_REGISTRY:
        by_cat.setdefault(t.category, []).append(t)
    return by_cat


def get_tool_by_name(name: str) -> ToolDefinition | None:
    """Get tool definition by name."""
    for t in KALI_TOOL_REGISTRY:
        if t.name == name:
            return t
    return None
