"""JS findings builder (Stage 1 minimal) — scaffold for future JS analysis.

Builds js_findings.md with sections for JS bundle inventory, framework markers,
API hints, and third-party integrations. Stage 1 parses HTML script src tags
if HTML is available; otherwise outputs placeholder template.
"""

import logging
import re
from html.parser import HTMLParser
from pathlib import Path

logger = logging.getLogger(__name__)


def build_js_findings(
    live_urls: list[str],
    html_path: str | Path | None = None,
) -> str:
    """Build js_findings.md report.

    Args:
        live_urls: List of live host URLs from http_probe or findings.
        html_path: Optional path to fetched HTML file for script src extraction.

    Returns:
        Markdown content for js_findings.md.
    """
    script_srcs: list[tuple[str, str]] = []  # (page_url, script_src)
    if html_path:
        script_srcs = _extract_script_srcs_from_html(Path(html_path), live_urls)

    has_js_data = bool(script_srcs)

    lines = [
        "# JavaScript Findings",
        "",
        "Stage 1 minimal report. Full JS crawling and analysis planned for Stage 2+.",
        "",
        "## JS Bundle Inventory",
        "",
    ]

    if has_js_data:
        seen: set[str] = set()
        for page_url, src in script_srcs:
            if src not in seen:
                seen.add(src)
                lines.append(f"- `{src}` (from: {page_url})")
        lines.append("")
    else:
        lines.extend([
            "No JavaScript analysis performed in Stage 1. Recommend running JS crawler in Stage 2.",
            "",
        ])

    lines.extend([
        "## Framework Markers",
        "",
    ])
    if has_js_data:
        frameworks = _infer_frameworks(script_srcs)
        if frameworks:
            for fw in sorted(frameworks):
                lines.append(f"- {fw}")
        else:
            lines.append("*No framework markers detected from script paths.*")
    else:
        lines.append("No JavaScript analysis performed in Stage 1. Recommend running JS crawler in Stage 2.")
    lines.append("")

    lines.extend([
        "## API Base URL Hints",
        "",
    ])
    if has_js_data:
        api_hints = _extract_api_hints(script_srcs)
        if api_hints:
            for hint in sorted(api_hints):
                lines.append(f"- `{hint}`")
        else:
            lines.append("*No API base URL hints found in script paths.*")
    else:
        lines.append("No JavaScript analysis performed in Stage 1. Recommend running JS crawler in Stage 2.")
    lines.append("")

    lines.extend([
        "## Third-Party Integrations",
        "",
    ])
    if has_js_data:
        third_party = _infer_third_party(script_srcs)
        if third_party:
            for tp in sorted(third_party):
                lines.append(f"- {tp}")
        else:
            lines.append("*No third-party integrations inferred from script paths.*")
    else:
        lines.append("No JavaScript analysis performed in Stage 1. Recommend running JS crawler in Stage 2.")
    lines.append("")

    lines.extend([
        "## Notes",
        "",
        f"- Live URLs scanned: {len(live_urls)}",
        "- Stage 1: script src extraction only. Stage 2+ will add full JS crawling, AST analysis, and secret detection.",
        "",
        "---",
        "",
        "*Generated by ARGUS Recon. JS analysis is minimal in Stage 1.*",
    ])

    return "\n".join(lines)


def _extract_script_srcs_from_html(
    html_path: Path,
    live_urls: list[str],
) -> list[tuple[str, str]]:
    """Extract script src URLs from HTML file. Returns list of (page_url, script_src)."""
    if not html_path.exists():
        logger.warning("HTML path does not exist", extra={"path": str(html_path)})
        return []

    try:
        content = html_path.read_text(encoding="utf-8", errors="replace")
    except OSError as e:
        logger.warning("Failed to read HTML", extra={"path": str(html_path), "error": str(e)})
        return []

    base_url = live_urls[0] if live_urls else ""
    srcs: list[str] = []
    parser = _ScriptSrcParser()
    parser.feed(content)
    srcs = parser.script_srcs

    return [(base_url, s) for s in srcs]


class _ScriptSrcParser(HTMLParser):
    """HTMLParser that collects script src attribute values."""

    def __init__(self) -> None:
        super().__init__()
        self.script_srcs: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag.lower() != "script":
            return
        for name, value in attrs:
            if name.lower() == "src" and value and value.strip():
                self.script_srcs.append(value.strip())
                break


def _infer_frameworks(script_srcs: list[tuple[str, str]]) -> set[str]:
    """Infer framework markers from script paths (e.g. react, vue, angular)."""
    frameworks: set[str] = set()
    framework_patterns = {
        "react": r"react|_react",
        "vue": r"vue|_vue",
        "angular": r"angular",
        "jquery": r"jquery",
        "next": r"next",
        "nuxt": r"nuxt",
    }
    for _, src in script_srcs:
        src_lower = src.lower()
        for name, pattern in framework_patterns.items():
            if re.search(pattern, src_lower):
                frameworks.add(name)
    return frameworks


def _extract_api_hints(script_srcs: list[tuple[str, str]]) -> set[str]:
    """Extract potential API base URL hints from script paths."""
    hints: set[str] = set()
    for _, src in script_srcs:
        if "/api/" in src.lower() or "api." in src.lower():
            parts = src.split("/")
            for i, p in enumerate(parts):
                if "api" in p.lower() and i > 0:
                    base = "/".join(parts[: i + 1])
                    if base and len(base) > 4:
                        hints.add(base)
    return hints


def _infer_third_party(script_srcs: list[tuple[str, str]]) -> set[str]:
    """Infer third-party integrations from script paths (CDNs, analytics, etc.)."""
    third_party: set[str] = set()
    known_domains = {
        "cdnjs", "cdn.jsdelivr", "unpkg", "googleapis", "gstatic",
        "cloudflare", "bootstrapcdn", "jsdelivr", "analytics", "gtag",
        "googletagmanager", "facebook", "twitter", "stripe", "recaptcha",
    }
    for _, src in script_srcs:
        src_lower = src.lower()
        for domain in known_domains:
            if domain in src_lower:
                third_party.add(domain)
    return third_party
