"""Stage 1 baseline contract for artifacts and report sections."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from typing import Any

STAGE1_BASELINE_ARTIFACTS: tuple[str, ...] = (
    "dns_summary.md",
    "subdomain_classification.csv",
    "live_hosts_detailed.csv",
    "tech_profile.csv",
    "headers_summary.md",
    "headers_detailed.csv",
    "tls_summary.md",
    "endpoint_inventory.csv",
    "route_inventory.csv",
    "public_pages.csv",
    "forms_inventory.csv",
    "params_inventory.csv",
    "js_bundle_inventory.csv",
    "js_routes.csv",
    "js_api_refs.csv",
    "js_integrations.csv",
    "js_config_hints.csv",
    "js_findings.md",
    "api_surface.csv",
    "input_surfaces.csv",
    "route_params_map.csv",
    "graphql_candidates.csv",
    "json_endpoint_candidates.csv",
    "frontend_backend_boundaries.md",
    "app_flow_hints.md",
    "host_security_posture.csv",
    "control_inconsistencies.md",
    "response_similarity.csv",
    "catch_all_evidence.md",
    "content_clusters.csv",
    "redirect_clusters.csv",
    "anomaly_validation.md",
    "anomaly_validation.csv",
    "hostname_behavior_matrix.csv",
    "stage2_preparation.md",
    "route_classification.csv",
    "stage3_readiness.json",
    "stage3_readiness.md",
    "anomalies.md",
    "anomalies_structured.json",
    "intel_findings.json",
    "intel_summary.md",
    "stage2_inputs.md",
    "stage2_structured.json",
    "ai_js_findings_analysis_raw.json",
    "ai_js_findings_analysis_normalized.json",
    "ai_js_findings_analysis_input_bundle.json",
    "ai_js_findings_analysis_validation.json",
    "ai_js_findings_analysis_rendered_prompt.md",
    "ai_parameter_input_analysis_raw.json",
    "ai_parameter_input_analysis_normalized.json",
    "ai_parameter_input_analysis_input_bundle.json",
    "ai_parameter_input_analysis_validation.json",
    "ai_parameter_input_analysis_rendered_prompt.md",
    "ai_api_surface_inference_raw.json",
    "ai_api_surface_inference_normalized.json",
    "ai_api_surface_inference_input_bundle.json",
    "ai_api_surface_inference_validation.json",
    "ai_api_surface_inference_rendered_prompt.md",
    "ai_headers_tls_summary_raw.json",
    "ai_headers_tls_summary_normalized.json",
    "ai_headers_tls_summary_input_bundle.json",
    "ai_headers_tls_summary_validation.json",
    "ai_headers_tls_summary_rendered_prompt.md",
    "ai_content_similarity_interpretation_raw.json",
    "ai_content_similarity_interpretation_normalized.json",
    "ai_content_similarity_interpretation_input_bundle.json",
    "ai_content_similarity_interpretation_validation.json",
    "ai_content_similarity_interpretation_rendered_prompt.md",
    "ai_anomaly_interpretation_raw.json",
    "ai_anomaly_interpretation_normalized.json",
    "ai_anomaly_interpretation_input_bundle.json",
    "ai_anomaly_interpretation_validation.json",
    "ai_anomaly_interpretation_rendered_prompt.md",
    "ai_stage2_preparation_summary_raw.json",
    "ai_stage2_preparation_summary_normalized.json",
    "ai_stage2_preparation_summary_input_bundle.json",
    "ai_stage2_preparation_summary_validation.json",
    "ai_stage2_preparation_summary_rendered_prompt.md",
    "ai_stage3_preparation_summary_raw.json",
    "ai_stage3_preparation_summary_normalized.json",
    "ai_stage3_preparation_summary_input_bundle.json",
    "ai_stage3_preparation_summary_validation.json",
    "ai_stage3_preparation_summary_rendered_prompt.md",
    "ai_persistence_manifest.json",
    "mcp_invocation_audit.jsonl",
    "mcp_invocation_audit_meta.json",
    "stage1_contract_baseline.json",
)

STAGE1_REPORT_SECTIONS: tuple[dict[str, Any], ...] = (
    {"index": 1, "id": "section-01-executive-summary", "title": "Executive Summary"},
    {"index": 2, "id": "section-02-scope-methodology", "title": "Scope & Methodology"},
    {"index": 3, "id": "section-03-domain-dns-findings", "title": "Domain and DNS Findings"},
    {"index": 4, "id": "section-04-subdomain-classification", "title": "Subdomain Classification"},
    {"index": 5, "id": "section-05-dns-validation-results", "title": "DNS Validation Results"},
    {"index": 6, "id": "section-06-live-host-analysis", "title": "Live Host Analysis"},
    {"index": 7, "id": "section-07-technology-profile", "title": "Technology Profile"},
    {"index": 8, "id": "section-08-javascript-frontend-analysis", "title": "JavaScript / Frontend Analysis"},
    {
        "index": 9,
        "id": "section-09-parameters-input-surfaces",
        "title": "Parameters and Input Surfaces",
    },
    {"index": 10, "id": "section-10-api-surface-mapping", "title": "API Surface Mapping"},
    {"index": 11, "id": "section-11-headers-cookies-tls-analysis", "title": "Headers / Cookies / TLS Analysis"},
    {
        "index": 12,
        "id": "section-12-content-similarity-and-routing-behavior",
        "title": "Content Similarity and Routing Behavior",
    },
    {"index": 13, "id": "section-13-anomaly-validation", "title": "Anomaly Validation"},
    {"index": 14, "id": "section-14-stage-2-preparation", "title": "Stage 2 Preparation"},
    {"index": 15, "id": "section-15-tools-and-ai-used", "title": "Tools & AI Used"},
    {"index": 16, "id": "section-16-intel-osint-enrichment", "title": "Intel/OSINT Enrichment"},
    {"index": 17, "id": "section-17-stage-3-readiness", "title": "Stage 3 Readiness"},
    {"index": 18, "id": "section-18-route-classification", "title": "Route Classification"},
)


def build_stage1_contract_snapshot(run_id: str, job_id: str, trace_id: str) -> str:
    """Build baseline Stage 1 contract snapshot for evidence trail."""
    payload = {
        "contract_name": "argus_stage1_recon_baseline",
        "contract_version": "2026-03-12-stage1-a",
        "generated_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "stage": "recon_stage1",
        "run_id": run_id,
        "job_id": job_id,
        "trace_id": trace_id,
        "run_link": f"recon://runs/{run_id}",
        "job_link": f"recon://jobs/{job_id}",
        "artifacts_required": list(STAGE1_BASELINE_ARTIFACTS),
        "report_sections_required": list(STAGE1_REPORT_SECTIONS),
        "notes": "Baseline contract snapshot captured without changing Stage 1 behavior.",
    }
    return json.dumps(payload, indent=2, ensure_ascii=False)
