#!/usr/bin/env python3
"""Build combined Stage 1 + Stage 2 + Stage 3 HTML report.

VA3UP-007: Next phase (Stage 3 inclusion) MUST NOT run when gate blocks.
If next_phase_gate.json exists and status != ready_for_next_phase, Stage 3
content is replaced with a blocking notice.
"""
from pathlib import Path
import html
import json

ARGUS_ROOT = Path(__file__).resolve().parent.parent
RECON = ARGUS_ROOT / "pentest_reports_svalbard" / "recon" / "svalbard-stage1"
REPORTS = ARGUS_ROOT / "pentest_reports_svalbard"


def _is_next_phase_allowed(recon_dir: Path) -> tuple[bool, str | None]:
    """Check next_phase_gate.json. Returns (allowed, blocking_status_or_none)."""
    path = recon_dir / "next_phase_gate.json"
    if not path.exists() or not path.is_file():
        return (True, None)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        status = data.get("status", "")
        blocked = data.get("blocked", True)
        if status == "ready_for_next_phase" and not blocked:
            return (True, None)
        return (False, status)
    except (json.JSONDecodeError, TypeError):
        return (True, None)


def main():
    stage1_path = RECON / "stage1_report.html"
    threat_path = RECON / "threat_model.md"
    va_path = RECON / "vulnerability_analysis.md"
    if not stage1_path.exists():
        print("Stage 1 report not found")
        return 1
    if not threat_path.exists():
        print("threat_model.md not found")
        return 1

    stage1 = stage1_path.read_text(encoding="utf-8", errors="replace")
    tm = threat_path.read_text(encoding="utf-8", errors="replace")
    tm_escaped = html.escape(tm)

    next_phase_allowed, blocking_status = _is_next_phase_allowed(RECON)
    if next_phase_allowed and va_path.exists():
        va = va_path.read_text(encoding="utf-8", errors="replace")
        va_escaped = html.escape(va)
    elif blocking_status:
        va = "[blocked]"
        va_escaped = html.escape(
            f"[Next phase blocked: {blocking_status}. "
            "Resolve gate conditions before including Stage 3 content.]"
        )
    else:
        va = va_path.read_text(encoding="utf-8", errors="replace") if va_path.exists() else ""
        va_escaped = html.escape(va) if va else ""

    stage2_block = f'''
    <section class="section" style="margin-top:3rem; padding:1.5rem; border-top:3px solid #1565c0; background:#e3f2fd;">
        <h1 style="color:#0d47a1; font-size:1.5rem; margin-top:0;">Этап 2: Моделирование угроз (Threat Modeling)</h1>
        <div class="meta"><p><strong>Target:</strong> svalbard.ca</p><p><strong>Methodology:</strong> ARGUS Threat Modeling — 9 AI tasks</p></div>
        <div style="background:#fff; padding:1rem; border-radius:6px; margin-top:1rem;"><pre style="white-space:pre-wrap; font-size:0.9rem; margin:0;">{tm_escaped}</pre></div>
    </section>

    '''
    stage3_block = f'''
    <section class="section" style="margin-top:3rem; padding:1.5rem; border-top:3px solid #c62828; background:#ffebee;">
        <h1 style="color:#b71c1c; font-size:1.5rem; margin-top:0;">Этап 3: Анализ уязвимостей (Vulnerability Analysis)</h1>
        <div class="meta"><p><strong>Target:</strong> svalbard.ca</p><p><strong>Methodology:</strong> ARGUS Vulnerability Analysis — 15 AI tasks</p></div>
        <div style="background:#fff; padding:1rem; border-radius:6px; margin-top:1rem;"><pre style="white-space:pre-wrap; font-size:0.9rem; margin:0;">{va_escaped}</pre></div>
    </section>

    ''' if va else ""

    stage1 = stage1.replace("    <footer style=", stage2_block + stage3_block + "    <footer style=")
    stage1 = stage1.replace("<title>Stage 1 Recon Report", "<title>Stage 1+2+3 Pentest Report", 1)
    stage1 = stage1.replace("Generated by ARGUS Recon.", "Generated by ARGUS Recon + Threat Modeling + Vulnerability Analysis.")

    out = REPORTS / "stage1-stage2-stage3-svalbard.html"
    out.write_text(stage1, encoding="utf-8")
    print(f"Written: {out}")
    return 0

if __name__ == "__main__":
    exit(main())
