"""Snapshot fixtures for byte-stable rendering tests.

This package is a *data-only* container for canonical golden files. Tests
under ``backend/tests/integration/`` assert byte-equality against the
fixtures stored here so determinism regressions surface immediately.

Fixture refresh policy:
    Snapshots are regenerated by running the relevant test suite with the
    ``ARGUS_SNAPSHOT_REFRESH=1`` environment variable. Every CI run uses
    the strict (read-only) path; only humans / explicit nightly tasks
    refresh the goldens.
"""
